name: news_swipe
description: Vertical swipe news app with Firebase
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  cached_network_image: ^3.3.1
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.0
  file_picker: ^8.1.2
  intl: ^0.19.0
  url_launcher: ^6.2.6
  webview_flutter: ^4.7.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
